apiVersion: apps/v1
kind: Deployment
metadata:
  name: jina-pod1-deployment
  labels:
    app: jina-pod1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jina-pod1
  template:
    metadata:
      labels:
        app: jina-pod1
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage

      containers:
      - name: pod1
#        stdin: true
#        tty: true
        image: us-central1-docker.pkg.dev/jina-sandbox/images/jina-base:latest
        volumeMounts:
          - mountPath: "/storage"
            name: storage
        terminationMessagePath: "/storage/logs_pod1"

        env:
          - name: LOG_PATH
            value: '/storage/logs.txt'

          - name: PORT_CTRL
            valueFrom:
              configMapKeyRef:
                name: jina-configmap
                key: port-ctrl
          - name: PORT_IN
            valueFrom:
              configMapKeyRef:
                name: jina-configmap
                key: port-in
          - name: HOST_OUT
            valueFrom:
              configMapKeyRef:
                name: jina-configmap
                key: gateway-host-name
          - name: PORT_OUT
            valueFrom:
              configMapKeyRef:
                name: jina-configmap
                key: port-out

        command: ["jina", "pod"]
        args: [
          "--uses", "/executors/pause.yaml",
          "--name", "pod1",
          "--port-ctrl", "$(PORT_CTRL)",

          "--host-in", "$(HOST_IN)",
          "--port-in", "$(PORT_IN)",
          "--host-out", "$(HOST_OUT)",
          "--port-out", "$(PORT_OUT)",

          "--socket-in", "SUB_BIND",
          "--socket-out", "PUSH_CONNECT"
        ]
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - jina ping 0.0.0.0 $PORT_CTRL
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 30
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - jina ping 0.0.0.0 $PORT_CTRL
          initialDelaySeconds: 30
          periodSeconds: 30 
          timeoutSeconds: 30
