apiVersion: apps/v1
kind: Deployment
metadata:
  name: jina-gateway-deployment
  labels:
    app: jina-gateway

spec:
  replicas: 1
  selector:
    matchLabels:
      app: jina-gateway

  template:
    metadata:
      labels:
        app: jina-gateway

    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: storage

      containers:
      - name: gateway
        image: us-central1-docker.pkg.dev/jina-sandbox/images/jina-base:latest
#        imagePullPolicy: Never
        volumeMounts:
          - mountPath: "/storage"
            name: storage
        terminationMessagePath: "/storage/logs_gateway"

        env:
          - name: PORT_IN
            valueFrom:
              configMapKeyRef:
                name: jina-configmap
                key: port-in
          - name: PORT_OUT
            valueFrom:
              configMapKeyRef:
                name: jina-configmap
                key: port-out
          - name: PORT_CTRL
            valueFrom:
              configMapKeyRef:
                name: jina-configmap
                key: port-ctrl
          - name: PORT_EXPOSE
            valueFrom:
              configMapKeyRef:
                name: jina-configmap
                key: gateway-port-expose
          - name: HOST_IN
            valueFrom:
              configMapKeyRef:
                name: jina-configmap
                key: pod1-host-name
          - name: HOST_OUT
            valueFrom:
              configMapKeyRef:
                name: jina-configmap
                key: pod0-host-name

        command: ["jina", "gateway"]
        args: [
          "--restful",
          "--name", "gateway",
          "--port-in", "$(PORT_OUT)",
          "--port-out", "$(PORT_IN)",
          "--port-ctrl", "$(PORT_CTRL)",
          "--port-expose", "$(PORT_EXPOSE)",
          "--host-in", "$(HOST_IN)",
          "--host-out", "$(HOST_OUT)",
          "--socket-in", "PULL_BIND",
          "--socket-out", "PUB_BIND"
        ]

        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - echo "success"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - echo "success"
          initialDelaySeconds: 30
          periodSeconds: 30
