apiVersion: v1
kind: Service
metadata:
  name: jina-expose-svc
spec:
  type: LoadBalancer

  ports:
  - port: 80
    targetPort: 30333
    name: gateway-port-expose
#    nodePort: 30333

  selector:
    app: jina-gateway
